version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw123
      POSTGRES_DB: touchbase
  # server:
  #   build: .
  #   links:
  #     - "db:postgres"
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ".:/app:rw"
  #     - "./data:/data:rw"
  #   command: python manage.py runserver 0.0.0.0:80
