# Generated by Django 3.0.5 on 2020-05-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base',
            new_name='TBase',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='base',
            new_name='t_base',
        ),
    ]
