---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/touchbasegen`}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pw123}
    driverclassname: ${jdbc_driver:org.postgresql.Driver}

jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: 'com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy'
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        hbm2ddl:
          auto: create
        show_sql: true
    packages-to-scan:
      - 'com.kf.touchbase.models.domain.postgres'
