---
micronaut:
  application:
    name: core-api
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
    netty:
      log-level: TRACE
  router:
    static-resources:
        swagger:
            paths: classpath:META-INF/swagger
            mapping: /swagger/**
  security:
    enabled: true
    token:
      enabled: true
      jwt:
        enabled: true
        signatures:
          jwks:
            auth0:
              url: https://${JWKS_AUTH_URL:cognito-idp.us-east-1.amazonaws.com/us-east-1_HnccgMQBx}/.well-known/jwks.json
        bearer:
          enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
  io:
    watch:
      paths: src/main
      restart: true
---
postgres:
  reactive:
    client:
      port: 5432
      host: kfdb1.cihodsllm9ip.us-east-1.rds.amazonaws.com
      database: touchbase
      user: ${DB_USER:postgres}
      password: xadgeV-wisvaz-caztu0
      maxSize: 5
 datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/touchbase`}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:Pw123}
    driverclassname: ${jdbc_driver:org.postgresql.Driver}

---
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
    packages-to-scan:
      - 'com.kf.touchbase.models.domain.postgres'
