---
micronaut:
  application:
    name: core-api
  server:
    netty:
      log-level: TRACE
  neo4j:
    uri: bolt://${NEO4J_HOST:localhost}
    username: ${NEO4J_USER:neo4j}
    password: ${NEO4J_PW:test}
  router:
    static-resources:
        swagger:
            paths: classpath:META-INF/swagger
            mapping: /swagger/**
  security:
    enabled: true
    login-handler: bearer
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            auth0:
              url: ${JWKS_AUTH_URL:https://touchbase-dev.auth0.com}/.well-known/jwks.json
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
  io:
    watch:
      paths: src/main
      restart: true
---
neo4j:
  uri: bolt://${NEO4J_HOST:localhost}
  username: ${NEO4J_USER:neo4j}
  password: ${NEO4J_PW:test}

---
graphql:
  enabled: true
  path: /graphql
  graphql-ws:
    enabled: true
    path: /graphql-ws
    keep-alive-enabled: true
    keep-alive-interval: 15s
  graphiql:
    enabled: true
    version: 0.13.2
    path: /graphiql
    template-path: classpath:graphiql/index.html
    template-parameters:
    page-title: GraphiQL

---
postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: touchbase
      user: postgres
      password: "pw123"
      maxSize: 5

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: postgres
    password: 'pw123'
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

