---
micronaut:
  application:
    name: core-api
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
    netty:
      log-level: TRACE
  router:
    static-resources:
        swagger:
            paths: classpath:META-INF/swagger
            mapping: /swagger/**
  security:
    enabled: true
    token:
      enabled: true
      jwt:
        enabled: true
        signatures:
          jwks:
            auth0:
              url: https://${JWKS_AUTH_URL:cognito-idp.us-east-1.amazonaws.com/us-east-1_HnccgMQBx}/.well-known/jwks.json
        bearer:
          enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
  io:
    watch:
      paths: src/main
      restart: true

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432`}/touchbase
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pw123}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

liquibase:
  enabled: ${MIGRATIONS:true}
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.yml'

jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: 'com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy'
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        hbm2ddl:
          auto: validate
    packages-to-scan:
      - 'com.kf.touchbase.models.domain.postgres'
