---
micronaut:
  openapi:
    config:
      file: openapi-dev.properties
  security:
    enabled: true
datasources:
  default:
    url: jdbc:h2:mem:touchbase;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: touchbase
    password: ''
    poolName: Hikari
#    autoCommit: false
    driverClassName: org.h2.Driver

redoc.enabled: false
swagger-ui.enabled: false


#liquibase:
#  enabled: ${MIGRATIONS:true}
#  datasources:
#    default:
#      change-log: 'classpath:db/liquibase-changelog.yml'

jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: 'com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy'
        cache:
          use_second_level_cache: false
        hbm2ddl:
          auto: create-drop
        show-sql: true
    packages-to-scan:
      - 'com.kf.touchbase.models.domain.postgres'
      - 'com.kf.touchbase.repository'
