INSERT INTO mission_template (id,
                              name,
                              description,
                              score_reward,
                              mission_type)
VALUES ('8f59d919-3830-4e1b-8a8c-be2b2b36a389',
        'easy mission',
        'this is a easy mission',
        10.0,
        'PERIODIC'),
       ('d657894d-c560-48c3-8d7a-bec719197374',
        'medium mission',
        'this is a medium difficulty mission',
        10.0,
        'PERIODIC');

INSERT INTO mission (id,
                     name,
                     description,
                     score_reward,
                     mission_type,
                     started_at,
                     created_at,
                     user_auth_key,
                     base)
VALUES ('287a7518-0547-45d8-a79e-9c920effbb31',
        'easy mission',
        'this is a easy mission',
        10.0,
        'PERIODIC',
        '08-20-2020',
        '08-21-2020',
        (SELECT tb_user.auth_key from tb_user where tb_user.username = 'arcq'),
        (SELECT id from base where base.name = 'base1')),
       ('52c6db7b-928d-462d-9a4d-683dcca8bdcb',
        'medium mission',
        'this is a medium difficulty mission',
        10.0,
        'PERIODIC',
        '08-20-2020',
        '08-21-2020',
        (SELECT tb_user.auth_key from tb_user where tb_user.username = 'sita'),
        (SELECT id from base where base.name = 'base2'));
