swagger: '2.0'
info:
  title: core-api
  version: '0.0'
paths:
  /api/v1/base:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BaseReq'
      responses:
        default:
          description: postBase default response
          schema:
            $ref: '#/definitions/Base'
      operationId: postBase
  '/api/v1/base/{baseId}':
    delete:
      produces:
        - application/json
      parameters:
        - format: uuid
          in: path
          name: baseId
          required: true
          type: string
      responses:
        default:
          description: makeBaseInactive default response
          schema:
            $ref: '#/definitions/Success'
      description: Not Implemented Yet
      operationId: makeBaseInactive
    patch:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BaseReq'
      responses:
        default:
          description: patchBase default response
          schema:
            $ref: '#/definitions/Base'
      operationId: patchBase
  '/api/v1/base/{baseId}/admin/{authId}':
    delete:
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
        - in: path
          name: authId
          required: true
          type: string
      responses:
        default:
          description: removeUserFromBaseAsAdmin default response
          schema:
            $ref: '#/definitions/Base'
      description: Not Implemented Yet
      operationId: removeUserFromBaseAsAdmin
    patch:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
        - in: path
          name: authId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BaseReq'
      responses:
        default:
          description: patchUserToBaseAsAdmin default response
          schema:
            $ref: '#/definitions/Base'
      description: Not Implemented Yet
      operationId: patchUserToBaseAsAdmin
    post:
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
        - in: path
          name: authId
          required: true
          type: string
      responses:
        default:
          description: addUserToBaseAsAdmin default response
          schema:
            $ref: '#/definitions/Base'
      description: Not Implemented Yet
      operationId: addUserToBaseAsAdmin
  /api/v1/baseJoin:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BaseJoinReq'
      responses:
        default:
          description: requestIntoBase default response
          schema:
            $ref: '#/definitions/BaseJoin'
      description: Not Implemented Yet
      operationId: requestIntoBase
  /api/v1/baseJoin/me:
    get:
      produces:
        - application/json
      parameters: []
      responses:
        default:
          description: getBases default response
          schema:
            items:
              $ref: '#/definitions/BaseJoin'
            type: array
      description: Not Implemented Yet
      operationId: getBases
  '/api/v1/baseJoin/{baseId}':
    delete:
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
      responses:
        default:
          description: deleteBaseInvite default response
          schema:
            $ref: '#/definitions/Success'
      description: Not Implemented Yet
      operationId: deleteBaseInvite
  /api/v1/mission/me:
    get:
      produces:
        - application/json
      parameters: []
      responses:
        default:
          description: getOwnMissions default response
          schema:
            items:
              $ref: '#/definitions/Mission'
            type: array
      description: Not Implemented Yet
      operationId: getOwnMissions
  /api/v1/mission/progress:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              progressReq:
                $ref: '#/definitions/ProgressReq'
            type: object
      responses:
        default:
          description: progressMission default response
          schema:
            $ref: '#/definitions/Mission'
      description: Not Implemented Yet
      operationId: progressMission
  /api/v1/user:
    get:
      produces:
        - application/json
      parameters:
        - in: query
          name: query
          required: true
          type: string
      responses:
        default:
          description: findAllPublic default response
          schema:
            items:
              $ref: '#/definitions/UserPublicRes'
            type: array
      operationId: findAllPublic
      summary: Search for users to add
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserReq'
      responses:
        default:
          description: postUser default response
          schema:
            $ref: '#/definitions/User'
      operationId: postUser
  /api/v1/user/me:
    get:
      produces:
        - application/json
      parameters: []
      responses:
        default:
          description: getMe default response
          schema:
            $ref: '#/definitions/User'
      operationId: getMe
  '/api/v1/user/{username}':
    get:
      produces:
        - application/json
      parameters:
        - in: path
          name: username
          required: true
          type: string
      responses:
        default:
          description: getUser default response
          schema:
            $ref: '#/definitions/User'
      operationId: getUser
definitions:
  Base:
    allOf:
      - $ref: '#/definitions/TouchBasePostgresEntity'
      - $ref: '#/definitions/TouchBasePostgresDomain'
      - properties:
          active:
            type: boolean
          imageUrl:
            type: string
          isActive:
            type: boolean
          members:
            items:
              $ref: '#/definitions/User'
            type: array
          name:
            type: string
          score:
            format: double
            type: number
        type: object
  BaseJoin:
    allOf:
      - $ref: '#/definitions/TouchBasePostgresEntity'
      - $ref: '#/definitions/TouchBasePostgresDomain'
      - properties:
          baseId:
            type: string
          baseJoinAction:
            $ref: '#/definitions/BaseJoinAction'
        type: object
  BaseJoinAction:
    enum:
      - Request
      - Invite
    type: string
  BaseJoinReq:
    properties:
      baseId:
        type: string
      baseJoinAction:
        $ref: '#/definitions/BaseJoinAction'
      userId:
        type: string
    type: object
  BaseReq:
    properties:
      imageUrl:
        type: string
      name:
        type: string
    type: object
  Mission:
    allOf:
      - $ref: '#/definitions/TouchBasePostgresDomain'
      - properties:
          description:
            type: string
          missonType:
            $ref: '#/definitions/MissonType'
          name:
            type: string
          scoreReward:
            format: double
            type: number
        type: object
  MissonType:
    enum:
      - PERIODIC
      - WEEKLY
      - ONE_TIME
    type: string
  ProgressReq:
    properties:
      value:
        format: int32
        type: integer
    type: object
  Success:
    properties:
      status:
        type: string
    type: object
  TouchBasePostgresDomain:
    properties:
      createdAt:
        format: date-time
        type: string
      updatedAt:
        format: date-time
        type: string
      uuid:
        format: uuid
        type: string
        x-nullable: true
    type: object
  TouchBasePostgresEntity:
    allOf:
      - $ref: '#/definitions/TouchBasePostgresDomain'
      - properties:
          admins:
            items:
              $ref: '#/definitions/User'
            type: array
          creator:
            $ref: '#/definitions/User'
        type: object
  User:
    allOf:
      - $ref: '#/definitions/TouchBasePostgresDomain'
      - properties:
          authId:
            type: string
          email:
            type: string
          firstName:
            type: string
          imageUrl:
            type: string
          lastName:
            type: string
          score:
            format: double
            type: number
          username:
            type: string
        type: object
  UserPublicRes:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      score:
        format: double
        type: number
      username:
        type: string
    type: object
  UserReq:
    properties:
      authId:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      score:
        format: double
        type: number
      username:
        type: string
    type: object
x-components: {}

