swagger: '2.0'
info:
  title: core-api
  version: '0.0'
paths:
  /api/v1/base:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BaseReq'
      responses:
        default:
          description: postBase default response
          schema:
            $ref: '#/definitions/Base'
      operationId: postBase
  '/api/v1/base/{baseId}':
    delete:
      produces:
        - application/json
      parameters:
        - format: uuid
          in: path
          name: baseId
          required: true
          type: string
      responses:
        default:
          description: makeBaseInactive default response
          schema:
            $ref: '#/definitions/Success'
      description: Not Implemented Yet
      operationId: makeBaseInactive
    patch:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BaseReq'
      responses:
        default:
          description: patchBase default response
          schema:
            $ref: '#/definitions/Base'
      operationId: patchBase
  '/api/v1/base/{baseId}/owner/{authId}':
    delete:
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
        - in: path
          name: authId
          required: true
          type: string
      responses:
        default:
          description: removeUserFromBaseAsOwner default response
          schema:
            $ref: '#/definitions/Base'
      description: Not Implemented Yet
      operationId: removeUserFromBaseAsOwner
    patch:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
        - in: path
          name: authId
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BaseReq'
      responses:
        default:
          description: patchUserToBaseAsOwner default response
          schema:
            $ref: '#/definitions/Base'
      description: Not Implemented Yet
      operationId: patchUserToBaseAsOwner
    post:
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
        - in: path
          name: authId
          required: true
          type: string
      responses:
        default:
          description: addUserToBaseAsOwner default response
          schema:
            $ref: '#/definitions/Base'
      description: Not Implemented Yet
      operationId: addUserToBaseAsOwner
  /api/v1/baseJoin:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/BaseJoinReq'
      responses:
        default:
          description: requestIntoBase default response
          schema:
            $ref: '#/definitions/BaseJoin'
      operationId: requestIntoBase
  /api/v1/baseJoin/me:
    get:
      produces:
        - application/json
      parameters: []
      responses:
        default:
          description: getBases default response
          schema:
            items:
              $ref: '#/definitions/BaseJoin'
            type: array
      operationId: getBases
      summary: Get all the joins and requests you've made
  '/api/v1/baseJoin/{baseId}':
    delete:
      produces:
        - application/json
      parameters:
        - in: path
          name: baseId
          required: true
          type: string
      responses:
        default:
          description: makeBaseInactive default response
          schema:
            $ref: '#/definitions/Success'
      operationId: makeBaseInactive
  /api/v1/mission/me:
    get:
      produces:
        - application/json
      parameters: []
      responses:
        default:
          description: getOwnMissions default response
          schema:
            items:
              $ref: '#/definitions/Mission'
            type: array
      operationId: getOwnMissions
  /api/v1/mission/progress:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              progressReq:
                $ref: '#/definitions/ProgressReq'
            type: object
      responses:
        default:
          description: progressMission default response
          schema:
            $ref: '#/definitions/Mission'
      operationId: progressMission
  /api/v1/person:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/PersonReq'
      responses:
        default:
          description: postPerson default response
          schema:
            $ref: '#/definitions/Person'
      operationId: postPerson
  /api/v1/person/me:
    get:
      produces:
        - application/json
      parameters: []
      responses:
        default:
          description: getMe default response
          schema:
            $ref: '#/definitions/Person'
      operationId: getMe
  '/api/v1/person/{username}':
    get:
      produces:
        - application/json
      parameters:
        - in: path
          name: username
          required: true
          type: string
      responses:
        default:
          description: getPerson default response
          schema:
            $ref: '#/definitions/Person'
      operationId: getPerson
definitions:
  Base:
    allOf:
      - $ref: '#/definitions/TouchBaseNeo4jEntity'
      - $ref: '#/definitions/TouchBaseNeo4jDomain'
      - properties:
          active:
            type: boolean
          imageUrl:
            type: string
          isActive:
            type: boolean
          members:
            items:
              $ref: '#/definitions/Person'
            type: array
          name:
            type: string
          score:
            format: double
            type: number
        type: object
  BaseJoin:
    allOf:
      - $ref: '#/definitions/TouchBasePostgresEntity'
      - $ref: '#/definitions/TouchBasePostgresDomain'
      - properties:
          baseId:
            type: string
          baseJoinAction:
            $ref: '#/definitions/BaseJoinAction'
        type: object
  BaseJoinAction:
    enum:
      - Request
      - Invite
    type: string
  BaseJoinReq:
    properties:
      baseId:
        type: string
      baseJoinAction:
        $ref: '#/definitions/BaseJoinAction'
      userId:
        type: string
    type: object
  BaseReq:
    properties:
      imageUrl:
        type: string
      name:
        type: string
    type: object
  Mission:
    allOf:
      - $ref: '#/definitions/TouchBaseNeo4jEntity'
      - $ref: '#/definitions/TouchBaseNeo4jDomain'
      - properties:
          description:
            type: string
          missonType:
            $ref: '#/definitions/MissonType'
          name:
            type: string
          scoreReward:
            format: double
            type: number
        type: object
  MissonType:
    enum:
      - PERIODIC
      - WEEKLY
      - ONE_TIME
    type: string
  Person:
    allOf:
      - $ref: '#/definitions/TouchBaseNeo4jDomain'
      - properties:
          authId:
            type: string
          bases:
            items:
              $ref: '#/definitions/Base'
            type: array
          created:
            items:
              $ref: '#/definitions/Base'
            type: array
          email:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          owns:
            items:
              $ref: '#/definitions/Base'
            type: array
          score:
            format: double
            type: number
          username:
            type: string
        type: object
  PersonReq:
    properties:
      authId:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      score:
        format: double
        type: number
      username:
        type: string
    type: object
  ProgressReq:
    properties:
      value:
        format: int32
        type: integer
    type: object
  Success:
    properties:
      status:
        type: string
    type: object
  TouchBaseNeo4jDomain:
    properties:
      createdAt:
        format: date-time
        type: string
      updatedAt:
        format: date-time
        type: string
      uuid:
        format: uuid
        type: string
    type: object
  TouchBaseNeo4jEntity:
    allOf:
      - $ref: '#/definitions/TouchBaseNeo4jDomain'
      - properties:
          creator:
            $ref: '#/definitions/Person'
          owner:
            $ref: '#/definitions/Person'
        type: object
  TouchBasePostgresDomain:
    properties:
      createdAt:
        format: date-time
        type: string
      updatedAt:
        format: date-time
        type: string
      uuid:
        format: uuid
        type: string
        x-nullable: true
    type: object
  TouchBasePostgresEntity:
    allOf:
      - $ref: '#/definitions/TouchBasePostgresDomain'
      - properties:
          creatorId:
            type: string
          ownerId:
            type: string
        type: object
x-components: {}

