#!/bin/bash

# for dev, programatically pull from heroku and update env variables
db_credentials=$(heroku pg:credentials:url DATABASE -a touchbase-dev | grep dbname)

env_vars="DB_NAME=$(echo $db_credentials | sed 's/^.*\dbname=\([^ ]*\) .*/\1/')
DB_USER=$(echo $db_credentials | sed 's/^.*\user=\([^ ]*\) .*/\1/')
DB_PASSWORD=$(echo $db_credentials | sed 's/^.*\password=\([^ ]*\) .*/\1/')
DB_HOST=$(echo $db_credentials | sed 's/^.*\host=\([^ ]*\) .*/\1/')
DB_PORT=$(echo $db_credentials | sed 's/^.*\port=\([^ ]*\) .*/\1/')
NEO4J_HOST=$(heroku config:get GRAPHENEDB_BOLT_URL -a touchbase-dev | sed   's/bolt:\/\///g')
NEO4J_USER=$(heroku config:get GRAPHENEDB_BOLT_USER -a touchbase-dev)
NEO4J_PW=$(heroku config:get GRAPHENEDB_BOLT_PASSWORD -a touchbase-dev)
NEO4J_ENCRYPTION_LEVEL=REQUIRED"

gcloud beta run services update touchbase --platform=managed \
  --update-env-vars=$(echo $env_vars | xargs | sed -e 's/ /,/g')
