---
micronaut:
  application:
    name: core-api
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
    netty:
      log-level: TRACE
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    enabled: true
    token:
      enabled: true
      jwt:
        enabled: true
        signatures:
          jwks:
            auth0:
              url: https://${JWKS_AUTH_URL:cognito-idp.us-east-1.amazonaws.com/us-east-1_HnccgMQBx}/.well-known/jwks.json
        bearer:
          enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()

jackson:
  serialization:
    write-dates-as-timestamps: false
  deserialization:
    fail-on-unknown-properties: false

aws:
  sns:
    region: usa-east-1
    topic: TouchbaseSNSTopic
    topics:
      test:
        topic: TouchbaseSNSTopicTest
  sqs:
    region: usa-east-1
    # related to service behaviour
    autoCreateQueue: false
    cache: false

    # related to default queue
    queue: TouchbaseQueue
    fifo: true
    delaySeconds: 0
    messageRetentionPeriod: 345600
    maximumMessageSize: 262144
    visibilityTimeout: 30

    queues:
      test:
        queue: TouchbaseQueueTest
  s3:
    region: usa-east-1
    bucket: touchbase

    buckets:
      test:
        bucket: test-bucket
