---
micronaut:
  application:
    name: core-api
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
    netty:
      log-level: TRACE
  router:
    static-resources:
        swagger:
            paths: classpath:META-INF/swagger
            mapping: /swagger/**
  security:
    enabled: true
    token:
      enabled: true
      jwt:
        enabled: true
        signatures:
          jwks:
            auth0:
              url: https://${JWKS_AUTH_URL:cognito-idp.us-east-1.amazonaws.com/us-east-1_HnccgMQBx}/.well-known/jwks.json
        bearer:
          enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()

jackson:
  serialization:
    write-dates-as-timestamps: false
  deserialization:
    fail-on-unknown-properties: false

aws:
  sns:
    region: usa-east-1
    topic: touchbase-topic
    topics:
      test:
        topic: touchbase-topic-test
