#!/bin/bash
db_credentials=$(heroku pg:credentials:url DATABASE -a touchbase-dev | grep dbname)

echo "DB_NAME=$(echo $db_credentials | sed 's/^.*\dbname=\([^ ]*\) .*/\1/')
DB_USER=$(echo $db_credentials | sed 's/^.*\user=\([^ ]*\) .*/\1/')
DB_PASSWORD=$(echo $db_credentials | sed 's/^.*\password=\([^ ]*\) .*/\1/')
DB_HOST=$(echo $db_credentials | sed 's/^.*\host=\([^ ]*\) .*/\1/')
DB_PORT=$(echo $db_credentials | sed 's/^.*\port=\([^ ]*\) .*/\1/')" > .env
docker build -t gcr.io/touchbase-276115/touchbase:latest -f Dockerfile .

docker push gcr.io/touchbase-276115/touchbase:latest

/* gcloud builds submit --tag gcr.io/touchbase-276115/touchbase */

gcloud beta run deploy touchbase --image gcr.io/touchbase-276115/touchbase --platform managed

rm .env
