branch-defaults:
  master:
    environment: touchbaseapp-dev
    group_suffix: null
environment-defaults:
  touchbase-dev:
    branch: null
    repository: null
  touchbaseapp-dev:
    branch: null
    repository: null
global:
  application_name: touchbase
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
