#!/bin/bash

#Dev Build Only
ECR_DOMAIN=670564539270.dkr.ecr.us-east-1.amazonaws.com
PROJECT_NAME=touchbase-core

#############################################
# 1. build open-api spec and copy to docs
#############################################

JAVA_TOOL_OPTIONS=-Dmicronaut.openapi.views.spec=redoc.enabled=true ./gradlew --no-daemon clean assemble
cp build/classes/java/main/META-INF/swagger/core-api-0.0.yml docs/swagger.yml

cd ./docs #./docs
redoc-cli bundle swagger.yml
mv redoc-static.html index.html
cd - #./

#############################################
# 2. build backenddocker container and upload
#############################################

./gradlew build

aws ecr get-login-password --region us-east-1 --profile default | docker login --username AWS --password-stdin $ECR_DOMAIN
docker build -t $ECR_DOMAIN/$PROJECT_NAME:latest -f Dockerfile .
docker push $ECR_DOMAIN/$PROJECT_NAME:latest

cd beanstalk
eb deploy
