openapi: 3.0.1
info:
  title: core-api
  version: "0.0"
paths:
  /api/v1/baseJoin:
    get:
      operationId: getOwnBaseJoins
      parameters: []
      responses:
        default:
          description: getOwnBaseJoins default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseJoinListRes'
    post:
      operationId: createBaseJoin
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseJoinReq'
        required: true
      responses:
        default:
          description: createBaseJoin default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseJoin'
  /api/v1/baseJoin/{baseJoinId}:
    post:
      operationId: acceptBaseJoin
      parameters:
      - name: baseJoinId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: acceptBaseJoin default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseMember'
    delete:
      operationId: declineBaseJoin
      parameters:
      - name: baseJoinId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: declineBaseJoin default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
  /api/v1/mission/me:
    get:
      description: Not Implemented Yet
      operationId: getOwnActiveMissions
      parameters: []
      responses:
        default:
          description: getOwnActiveMissions default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mission'
  /api/v1/mission/progress:
    post:
      description: Not Implemented Yet
      operationId: progressMission
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                progressReq:
                  $ref: '#/components/schemas/ProgressReq'
        required: true
      responses:
        default:
          description: progressMission default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mission'
  /api/v1/base:
    get:
      operationId: getOwnBases
      parameters: []
      responses:
        default:
          description: getOwnBases default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRes_Base_'
    post:
      operationId: postBase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseReq'
        required: true
      responses:
        default:
          description: postBase default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Base'
  /api/v1/base/{baseId}:
    get:
      operationId: getBaseIfOwn
      parameters:
      - name: baseId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: getBaseIfOwn default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Base'
  /api/v1/upload/signed-url:
    get:
      operationId: upload
      parameters:
      - name: key
        in: query
        required: true
        schema:
          type: string
      responses:
        default:
          description: upload default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignedUrlRes'
  /api/v1/user/me:
    get:
      operationId: getMe
      parameters: []
      responses:
        default:
          description: getMe default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/v1/user:
    put:
      summary: Update user
      operationId: putUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserReq'
        required: true
      responses:
        default:
          description: putUser default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    post:
      summary: Create user
      operationId: postUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserReq'
        required: true
      responses:
        default:
          description: postUser default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    BaseJoinListRes:
      type: object
      properties:
        requestsList:
          type: array
          items:
            $ref: '#/components/schemas/BaseJoin'
        invitesList:
          type: array
          items:
            $ref: '#/components/schemas/BaseJoin'
    TouchBasePostgresDomain:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        id:
          type: string
          format: uuid
          nullable: true
        creator:
          $ref: '#/components/schemas/User'
    User:
      allOf:
      - $ref: '#/components/schemas/TouchBasePostgresDomain'
      - type: object
        properties:
          createdAt:
            type: string
            format: date-time
          updatedAt:
            type: string
            format: date-time
          id:
            type: string
            format: uuid
            nullable: true
          authKey:
            type: string
          username:
            type: string
          email:
            type: string
          score:
            type: number
            format: double
          firstName:
            type: string
          lastName:
            type: string
          imageUrl:
            type: string
    BaseJoin:
      allOf:
      - $ref: '#/components/schemas/TouchBasePostgresDomain'
      - type: object
        properties:
          base:
            $ref: '#/components/schemas/Base'
          joiningUser:
            $ref: '#/components/schemas/User'
          baseJoinAction:
            $ref: '#/components/schemas/BaseJoinAction'
    Base:
      allOf:
      - $ref: '#/components/schemas/TouchBasePostgresDomain'
      - type: object
        properties:
          name:
            type: string
          score:
            type: number
            format: double
          imageUrl:
            type: string
          active:
            type: boolean
          members:
            type: array
            items:
              $ref: '#/components/schemas/BaseMember'
          chats:
            type: array
            items:
              $ref: '#/components/schemas/Chat'
    BaseMember:
      allOf:
      - $ref: '#/components/schemas/TouchBasePostgresDomain'
      - type: object
        properties:
          base:
            $ref: '#/components/schemas/Base'
          user:
            $ref: '#/components/schemas/User'
          role:
            $ref: '#/components/schemas/Role'
    Role:
      type: string
      enum:
      - MEMBER
      - ADMIN
    Chat:
      allOf:
      - $ref: '#/components/schemas/TouchBasePostgresDomain'
      - type: object
        properties:
          base:
            $ref: '#/components/schemas/Base'
          chatpiChatId:
            type: string
    BaseJoinAction:
      type: string
      enum:
      - REQUEST
      - INVITE
    BaseJoinReq:
      type: object
      properties:
        baseId:
          type: string
          format: uuid
        userAuthKey:
          type: string
        baseJoinAction:
          $ref: '#/components/schemas/BaseJoinAction'
    Success:
      type: object
      properties:
        status:
          type: string
    Mission:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        id:
          type: string
          format: uuid
          nullable: true
        startedAt:
          type: string
          format: date-time
        assignedUser:
          $ref: '#/components/schemas/User'
        assignedBase:
          $ref: '#/components/schemas/Base'
        storedMissionTemplate:
          $ref: '#/components/schemas/MissionTemplate'
    MissionTemplate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        scoreReward:
          type: number
          format: double
        missionType:
          $ref: '#/components/schemas/MissionType'
    MissionType:
      type: string
      enum:
      - PERIODIC
      - WEEKLY
      - ONE_TIME
    ProgressReq:
      type: object
      properties:
        value:
          type: integer
          format: int32
    ListRes_Base_:
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/Base'
    BaseReq:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
    SignedUrlRes:
      type: object
      properties:
        url:
          type: string
    UserReq:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        score:
          type: number
          format: double
        firstName:
          type: string
        lastName:
          type: string
        imageUrl:
          type: string
