openapi: 3.0.1
info:
  title: core-api
  version: "0.0"
paths:
  /api/v1/base:
    post:
      operationId: postBase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseReq'
        required: true
      responses:
        default:
          description: postBase default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Base'
  /api/v1/base/{baseId}:
    delete:
      description: Not Implemented Yet
      operationId: makeBaseInactive
      parameters:
      - name: baseId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: makeBaseInactive default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
    patch:
      operationId: patchBase
      parameters:
      - name: baseId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseReq'
        required: true
      responses:
        default:
          description: patchBase default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Base'
  /api/v1/base/{baseId}/owner/{authId}:
    post:
      description: Not Implemented Yet
      operationId: addUserToBaseAsOwner
      parameters:
      - name: baseId
        in: path
        required: true
        schema:
          type: string
      - name: authId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: addUserToBaseAsOwner default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Base'
    delete:
      description: Not Implemented Yet
      operationId: removeUserFromBaseAsOwner
      parameters:
      - name: baseId
        in: path
        required: true
        schema:
          type: string
      - name: authId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: removeUserFromBaseAsOwner default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Base'
    patch:
      description: Not Implemented Yet
      operationId: patchUserToBaseAsOwner
      parameters:
      - name: baseId
        in: path
        required: true
        schema:
          type: string
      - name: authId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseReq'
        required: true
      responses:
        default:
          description: patchUserToBaseAsOwner default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Base'
  /api/v1/baseJoin/me:
    get:
      description: Not Implemented Yet
      operationId: getBases
      parameters: []
      responses:
        default:
          description: getBases default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BaseJoin'
  /api/v1/baseJoin:
    post:
      description: Not Implemented Yet
      operationId: requestIntoBase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseJoinReq'
        required: true
      responses:
        default:
          description: requestIntoBase default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseJoin'
  /api/v1/baseJoin/{baseId}:
    delete:
      description: Not Implemented Yet
      operationId: deleteBaseInvite
      parameters:
      - name: baseId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: deleteBaseInvite default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
  /api/v1/person:
    get:
      summary: Search for users to add
      operationId: findAllPublic
      parameters:
      - name: query
        in: query
        required: true
        schema:
          type: string
      responses:
        default:
          description: findAllPublic default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonPublicRes'
    post:
      operationId: postPerson
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonReq'
        required: true
      responses:
        default:
          description: postPerson default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
  /api/v1/person/me:
    get:
      operationId: getMe
      parameters: []
      responses:
        default:
          description: getMe default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
  /api/v1/person/{username}:
    get:
      operationId: getPerson
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: getPerson default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
  /api/v1/mission/me:
    get:
      description: Not Implemented Yet
      operationId: getOwnMissions
      parameters: []
      responses:
        default:
          description: getOwnMissions default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mission'
  /api/v1/mission/progress:
    post:
      description: Not Implemented Yet
      operationId: progressMission
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                progressReq:
                  $ref: '#/components/schemas/ProgressReq'
        required: true
      responses:
        default:
          description: progressMission default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mission'
components:
  schemas:
    TouchBaseNeo4jDomain:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    TouchBaseNeo4jEntity:
      allOf:
      - $ref: '#/components/schemas/TouchBaseNeo4jDomain'
      - type: object
        properties:
          creator:
            $ref: '#/components/schemas/Person'
          owner:
            $ref: '#/components/schemas/Person'
    Person:
      allOf:
      - $ref: '#/components/schemas/TouchBaseNeo4jDomain'
      - type: object
        properties:
          authId:
            type: string
          username:
            type: string
          email:
            type: string
          score:
            type: number
            format: double
          firstName:
            type: string
          lastName:
            type: string
          bases:
            type: array
            items:
              $ref: '#/components/schemas/Base'
          created:
            type: array
            items:
              $ref: '#/components/schemas/Base'
          owns:
            type: array
            items:
              $ref: '#/components/schemas/Base'
    Base:
      allOf:
      - $ref: '#/components/schemas/TouchBaseNeo4jEntity'
      - $ref: '#/components/schemas/TouchBaseNeo4jDomain'
      - type: object
        properties:
          name:
            type: string
          score:
            type: number
            format: double
          imageUrl:
            type: string
          active:
            type: boolean
          members:
            type: array
            items:
              $ref: '#/components/schemas/Person'
          isActive:
            type: boolean
    BaseReq:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
    Success:
      type: object
      properties:
        status:
          type: string
    TouchBasePostgresDomain:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    TouchBasePostgresEntity:
      allOf:
      - $ref: '#/components/schemas/TouchBasePostgresDomain'
      - type: object
        properties:
          ownerId:
            type: string
          creatorId:
            type: string
    BaseJoin:
      allOf:
      - $ref: '#/components/schemas/TouchBasePostgresEntity'
      - $ref: '#/components/schemas/TouchBasePostgresDomain'
      - type: object
        properties:
          baseId:
            type: string
          baseJoinAction:
            $ref: '#/components/schemas/BaseJoinAction'
    BaseJoinAction:
      type: string
      enum:
      - Request
      - Invite
    BaseJoinReq:
      type: object
      properties:
        baseId:
          type: string
        userId:
          type: string
        baseJoinAction:
          $ref: '#/components/schemas/BaseJoinAction'
    PersonPublicRes:
      type: object
      properties:
        score:
          type: number
          format: double
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
    PersonReq:
      type: object
      properties:
        authId:
          type: string
        email:
          type: string
        score:
          type: number
          format: double
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
    Mission:
      allOf:
      - $ref: '#/components/schemas/TouchBaseNeo4jEntity'
      - $ref: '#/components/schemas/TouchBaseNeo4jDomain'
      - type: object
        properties:
          name:
            type: string
          description:
            type: string
          scoreReward:
            type: number
            format: double
          missonType:
            $ref: '#/components/schemas/MissonType'
    MissonType:
      type: string
      enum:
      - PERIODIC
      - WEEKLY
      - ONE_TIME
    ProgressReq:
      type: object
      properties:
        value:
          type: integer
          format: int32
